# Generated by Django 5.2.17 on 2026-09-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_document_file_document_is_active_document_is_indexed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_indexed',
        ),
    ]
